### ISSUE TITLE
Std proc dialog not opening in release candidate for v1.1

### ISSUE THREAD

**Issue by Diego635** [jaminzoda/terra-antiqua#232]
The other dialogs open correctly but when clicking on the std proc tools this pops up:

> Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.

The detail of the Python error is:

  

>  File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/base_dialog.py", line 100, in addVariantParameter
>               param = param(label)
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/widgets.py", line 357, in __init__
>               super().__init__(parent)
>              TypeError: QComboBox(parent: QWidget = None): argument 1 has unexpected type 'str'
>              
>              During handling of the above exception, another exception occurred:
>              
>              Traceback (most recent call last):
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/core/terra_antiqua.py", line 322, in initStandardProcessing
>               self.settings)
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/core/algorithm_provider.py", line 28, in __init__
>               self.dlg = dlg()
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/standard_proc_dlg.py", line 27, in __init__
>               self.defineParameters()
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/standard_proc_dlg.py", line 155, in defineParameters
>               self.colorPalette = self.addVariantParameter(TaColorSchemeWidget, "Change map symbology", "Color palette:")
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/base_dialog.py", line 104, in addVariantParameter
>               param = param()
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/widgets.py", line 360, in __init__
>               self.populateColorSchemes()
>               File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/gui/widgets.py", line 370, in populateColorSchemes
>               color_scheme_name = lines[0].strip()
>              IndexError: list index out of range

**Comment by Diego635** [comment]
Problem solved
