### ISSUE TITLE
QGIS freezes when creating mountain range with a shapefile with several polygons.

### ISSUE THREAD

**Issue by Diego635** [jaminzoda/terra-antiqua#249]
I tried two options: first I selected 1 polygon from the layer and checked the box to use only selected layer, then I tried to use all polygons in the layer. None worked. See below both warnings from the Log Messages Panel
The shapefile I used is the _masks for small regions_ from the sample data bundle.

This error was reported by a user running QGIS 3.10 on MacOS Monterey
I was able to replicate it running QGIS 3.22 on MacOS Ventura

I tried to run the tool several times and each time it was freezing on a different point (16%, 15%, 50%, etc.). Once it even crashed QGIS.

```
2022-12-03T16:57:35     WARNING    Traceback (most recent call last):
              File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/core/create_tb.py", line 65, in run
              self.createMountainRange()
              File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/core/create_tb.py", line 719, in createMountainRange
              elev = elev+np.random.randint(min_bound,max_bound)
              File "mtrand.pyx", line 747, in numpy.random.mtrand.RandomState.randint
              File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64
             ValueError: low >= high
             
2022-12-03T17:03:07     WARNING    Traceback (most recent call last):
              File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/core/create_tb.py", line 65, in run
              self.createMountainRange()
              File "/Users/diego/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terra_antiqua/core/create_tb.py", line 668, in createMountainRange
              total = progress_unit*0.1/points_dist_elev_layer.featureCount() if points_dist_elev_layer.featureCount() else 0
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
```

**Comment by jaminzoda** [comment]
This error is related to invalid geometries within the supplied mask layer. Need to check for invalid geometries and fix them before running the densification algorithm.
